version: "2"
services:
  node:
    build: .
    ports:
      - 5000:5000
    volumes:
      - /chaindata/:/app/chaindata
    environment:
      MONGODB_HOST: mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    ports:
      - 9200:9200
